style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/lamassuiot/lamassuiot
options:
  commits:
    filters:
      Type:
        - bump
        - remove
        - fix
        - feat
        - security
        - test
        - chore
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      bump: Bump Versions
      remove: Removed
      security: Security Fixes
      test: Tests
      chore: Chores
  header:
    pattern: "^((\\w+)\\s.*)$"
    pattern_maps:
      - Subject
      - Type
  notes:
    keywords:
      - BREAKING CHANGE