name: DMS Enroller - develop workflow

on:
  push:
    branches:
      - develop
    paths:
        - 'pkg/dms-enroller/**'
        - 'main/dms-enroller/**'
  workflow_call:

jobs:
  lamassu_dms_enroller_unit_testing:
    name: DMS Enroller Unit Testing
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 
      
      - name: Set up gotestfmt
        run: go install github.com/haveyoudebuggedit/gotestfmt/v2/cmd/gotestfmt@v2.3.1

      - name: Run Go Unit Tests
        run: |
          set -eo pipefail
          go test -json -v ./pkg/dms-enroller/server/api/service/ | gotestfmt